require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'GitHub_RN' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
#    :hermes_enabled => flags[:hermes_enabled],
    :hermes_enabled => false, #解决启用:hermes 后无法开启浏览器调试的问题 https://github.com/facebook/react-native/issues/34624
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  #必须集成
  pod 'UMCommon'
  pod 'UMDevice'

  # U-Share SDK UI模块（分享面板，建议添加）
  pod 'UMShare/UI'

  #集成微信(完整版14.4M)
  pod 'UMShare/Social/WeChat'

  #集成QQ/QZone/TIM(完整版7.6M)
  pod 'UMShare/Social/QQ'

  #集成新浪微博(完整版25.3M)
  pod 'UMShare/Social/Sina'

  #集成新浪微博(精简版1M)
  pod 'UMShare/Social/ReducedSina'

  #集成邮件
  pod 'UMShare/Social/Email'

  #集成短信
  pod 'UMShare/Social/SMS'

  target 'GitHub_RNTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
